permalink:  /:title/

url: 'http://inspiring.online'

# Title tag variables
title: Inspiring Online
tagline: 'Inspiring things, on the online landscape.'

# Links tag variables
twitter: "twholman"
github:  "tholman"

# Other external links
analytics_tracking_id: "UA-22825241-1"

# Misc variables
highlighter: 'pygments'
encoding: utf-8

# Number of posts on each page.
paginate: 10
